name: WODDice
favicon: null
layout_spectrum: 0.5659553310833871
typography_spectrum: 0.639632333535701
title: WODDice®
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#007dbd'
    - '#000000'
    - '#ff0a1c'
    - '#fa6e7f'
  brandStrength: 0.8960504478309304
  lightness: 0.5514315948821604
  saturation: 0.3862174581736326
  rhythmicContrast: 0.46428407123312354
purpose: []
